//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class CharacterState {

        public CharacterState()
        {
            OnCreated();
        }

        public virtual int CharacterId
        {
            get;
            set;
        }

        public virtual int Hp
        {
            get;
            set;
        }

        public virtual int Mp
        {
            get;
            set;
        }

        public virtual int Stamina
        {
            get;
            set;
        }

        public virtual int MaxHp
        {
            get;
            set;
        }

        public virtual int MaxMp
        {
            get;
            set;
        }

        public virtual int MaxStamina
        {
            get;
            set;
        }

        public virtual int? EquipedWeaponId
        {
            get;
            set;
        }

        public virtual int? EquipedArmorId
        {
            get;
            set;
        }

        public virtual int? EquipedAmuletId
        {
            get;
            set;
        }

        public virtual int XPos
        {
            get;
            set;
        }

        public virtual int YPos
        {
            get;
            set;
        }

        public virtual int? EquipedOffhandId
        {
            get;
            set;
        }

        public virtual Character Character
        {
            get;
            set;
        }

        public virtual ExistingItem ExistingItem_EquipedAmuletId
        {
            get;
            set;
        }

        public virtual ExistingItem ExistingItem_EquipedArmorId
        {
            get;
            set;
        }

        public virtual ExistingItem ExistingItem_EquipedOffhandId
        {
            get;
            set;
        }

        public virtual ExistingItem ExistingItem_EquipedWeaponId
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
