//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class Monster {

        public Monster()
        {
            this.ExistingMonsters = new List<ExistingMonster>();
            OnCreated();
        }

        public virtual int MonsterId
        {
            get;
            set;
        }

        public virtual string MonsterName
        {
            get;
            set;
        }

        public virtual int Str
        {
            get;
            set;
        }

        public virtual int Dex
        {
            get;
            set;
        }

        public virtual int Int
        {
            get;
            set;
        }

        public virtual int Con
        {
            get;
            set;
        }

        public virtual int Cha
        {
            get;
            set;
        }

        public virtual int Hp
        {
            get;
            set;
        }

        public virtual int Damage
        {
            get;
            set;
        }

        public virtual int Armor
        {
            get;
            set;
        }

        public virtual bool InMeadow
        {
            get;
            set;
        }

        public virtual bool InForest
        {
            get;
            set;
        }

        public virtual bool InDesert
        {
            get;
            set;
        }

        public virtual bool InTown
        {
            get;
            set;
        }

        public virtual int RarityLevel
        {
            get;
            set;
        }

        public virtual IList<ExistingMonster> ExistingMonsters
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
