//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class ExistingMonster {

        public ExistingMonster()
        {
            OnCreated();
        }

        public virtual int ExistingMonsterId
        {
            get;
            set;
        }

        public virtual int MonsterId
        {
            get;
            set;
        }

        public virtual int XPos
        {
            get;
            set;
        }

        public virtual int YPos
        {
            get;
            set;
        }

        public virtual int Damaged
        {
            get;
            set;
        }

        public virtual Monster Monster
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
