//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class Character {

        public Character()
        {
            this.ExistingItems = new List<ExistingItem>();
            OnCreated();
        }

        public virtual int CharacterId
        {
            get;
            set;
        }

        public virtual string Nickname
        {
            get;
            set;
        }

        public virtual System.DateTime Birthdate
        {
            get;
            set;
        }

        public virtual int UserId
        {
            get;
            set;
        }

        public virtual User User
        {
            get;
            set;
        }

        public virtual CharacterInfo CharacterInfo
        {
            get;
            set;
        }

        public virtual CharacterState CharacterState
        {
            get;
            set;
        }

        public virtual IList<ExistingItem> ExistingItems
        {
            get;
            set;
        }
        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
