//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class Item {

        public Item()
        {
            this.ExistingItems = new List<ExistingItem>();
            OnCreated();
        }

        public virtual int ItemId
        {
            get;
            set;
        }

        public virtual int? Damage
        {
            get;
            set;
        }

        public virtual int? Armor
        {
            get;
            set;
        }

        public virtual int? StrBonus
        {
            get;
            set;
        }

        public virtual int? DexBonus
        {
            get;
            set;
        }

        public virtual int? IntBonus
        {
            get;
            set;
        }

        public virtual int? ConBonus
        {
            get;
            set;
        }

        public virtual int? ChaBonus
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual int Weight
        {
            get;
            set;
        }

        public virtual int Worth
        {
            get;
            set;
        }

        public virtual string Type
        {
            get;
            set;
        }

        public virtual int RarityLevel
        {
            get;
            set;
        }

        public virtual IList<ExistingItem> ExistingItems
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
