//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class CharacterInfo {

        public CharacterInfo()
        {
            this.Gold = 0;
            OnCreated();
        }

        public virtual int CharacterId
        {
            get;
            set;
        }

        public virtual string Race
        {
            get;
            set;
        }

        public virtual string Sex
        {
            get;
            set;
        }

        public virtual int? Level
        {
            get;
            set;
        }

        public virtual int Str
        {
            get;
            set;
        }

        public virtual int Dex
        {
            get;
            set;
        }

        public virtual int Int
        {
            get;
            set;
        }

        public virtual int Con
        {
            get;
            set;
        }

        public virtual int Cha
        {
            get;
            set;
        }

        public virtual int Exp
        {
            get;
            set;
        }

        public virtual int Gold
        {
            get;
            set;
        }

        public virtual int? StatPoints
        {
            get;
            set;
        }

        public virtual Character Character
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
