//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class ItemType {

        public ItemType()
        {
            this.ExistingItems = new List<ExistingItem>();
            OnCreated();
        }

        public virtual int ItemTypeId
        {
            get;
            set;
        }

        public virtual string ItemTypeName
        {
            get;
            set;
        }

        public virtual double DamageModifier
        {
            get;
            set;
        }

        public virtual double ArmorModifier
        {
            get;
            set;
        }

        public virtual int? StrModifier
        {
            get;
            set;
        }

        public virtual int? DexModifier
        {
            get;
            set;
        }

        public virtual int? IntModifier
        {
            get;
            set;
        }

        public virtual int? ConModifier
        {
            get;
            set;
        }

        public virtual int? ChaModifier
        {
            get;
            set;
        }

        public virtual double WorthModifier
        {
            get;
            set;
        }

        public virtual double WeightModifier
        {
            get;
            set;
        }

        public virtual int TypeRarityLevel
        {
            get;
            set;
        }

        public virtual int AdditionalWorth
        {
            get;
            set;
        }

        public virtual IList<ExistingItem> ExistingItems
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
