//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19.05.2019 13:05:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace gameModel
{
    public partial class ExistingItem {

        public ExistingItem()
        {
            this.CharacterStates_EquipedAmuletId = new List<CharacterState>();
            this.CharacterStates_EquipedArmorId = new List<CharacterState>();
            this.CharacterStates_EquipedOffhandId = new List<CharacterState>();
            this.CharacterStates_EquipedWeaponId = new List<CharacterState>();
            OnCreated();
        }

        public virtual int ExistingItemId
        {
            get;
            set;
        }

        public virtual int ItemId
        {
            get;
            set;
        }

        public virtual int ItemTypeId
        {
            get;
            set;
        }

        public virtual int? CharacterId
        {
            get;
            set;
        }

        public virtual IList<CharacterState> CharacterStates_EquipedAmuletId
        {
            get;
            set;
        }

        public virtual IList<CharacterState> CharacterStates_EquipedArmorId
        {
            get;
            set;
        }

        public virtual IList<CharacterState> CharacterStates_EquipedOffhandId
        {
            get;
            set;
        }

        public virtual IList<CharacterState> CharacterStates_EquipedWeaponId
        {
            get;
            set;
        }

        public virtual Item Item
        {
            get;
            set;
        }

        public virtual Character Character
        {
            get;
            set;
        }

        public virtual ItemType ItemType
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
